### ISSUE TITLE
Results should be rendered as PDFs

### ISSUE THREAD

**Issue by JanX2** [johnno1962/XprobePlugin#3]
At least by default. They are resolution-independent and searchable. This is very easy to do with GraphVis.

**Comment by johnno1962** [comment]
Can you give me the command line for that? I could add it.

**Comment by JanX2** [comment]
Just swap “png” for “pdf” mostly. I did this here recently:

https://github.com/JanX2/ObjectGraph-Xcode/commits/janx2/PDF-output

Looks like modifying “-graphpng:” is more work than that though.

**Comment by johnno1962** [comment]
I’ve pushed this change. PDF is altogether a beter render format. Thanks!

**Comment by JanX2** [comment]
Awesome!
