### ISSUE TITLE
Can’t install

### ISSUE THREAD

**Issue by JanX2** [johnno1962/XprobePlugin#4]
Alcatraz fails to install and manually buildings fails currently. This appears to be the issue:

				LIBRARY_SEARCH_PATHS = (
					"$(inherited)",
					/Users/johnholdsworth/Developer/XprobePlugin,
				);

This is in “XprobeBundle.xcodeproj”.

**Comment by johnno1962** [comment]
!

**Comment by johnno1962** [comment]
can you try now?

**Comment by johnno1962** [comment]
There is also a problem with Alcatraz which may give you a message about nibs

**Comment by JanX2** [comment]
Works with current HEAD after fixing my codesigning setup for the project.

BTW: Did I read the script wrong or is this hardcoded to build Debug builds only?

**Comment by JanX2** [comment]
Great fun working with you. :)

**Comment by johnno1962** [comment]
Thanks for your help Jan. We got some things fixed!
